# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'librabry.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 609)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 470, 71, 61))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Theme.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(45, 45))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 50, 71, 61))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/today.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(22, 140, 71, 51))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(22, 220, 71, 51))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(60, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 380, 71, 61))
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(120, 40, 911, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_18.setGeometry(QtCore.QRect(20, 20, 151, 41))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.comboBox_9 = QtWidgets.QComboBox(self.tab)
        self.comboBox_9.setGeometry(QtCore.QRect(420, 21, 73, 31))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab)
        self.pushButton_14.setGeometry(QtCore.QRect(682, 20, 131, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 80, 911, 361))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(520, 30, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.comboBox_10 = QtWidgets.QComboBox(self.tab)
        self.comboBox_10.setGeometry(QtCore.QRect(570, 21, 73, 31))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(370, 30, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_30.setGeometry(QtCore.QRect(200, 20, 151, 41))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab)
        self.pushButton_29.setGeometry(QtCore.QRect(640, 440, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 921, 491))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 921, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_27.setGeometry(QtCore.QRect(680, 420, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 60, 191, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(540, 60, 291, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_3.setGeometry(QtCore.QRect(540, 141, 291, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_4.setGeometry(QtCore.QRect(540, 200, 291, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_5.setGeometry(QtCore.QRect(540, 260, 291, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(540, 330, 291, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_7.setGeometry(QtCore.QRect(370, 400, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(450, 70, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(460, 150, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(464, 210, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(460, 270, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(450, 340, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textEdit = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit.setGeometry(QtCore.QRect(40, 150, 301, 231))
        self.textEdit.setObjectName("textEdit")
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        self.label_36.setGeometry(QtCore.QRect(40, 130, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_10 = QtWidgets.QLabel(self.tab_6)
        self.label_10.setGeometry(QtCore.QRect(470, 280, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_6.setGeometry(QtCore.QRect(570, 280, 291, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 120, 191, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(480, 230, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(460, 330, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_7.setGeometry(QtCore.QRect(570, 230, 291, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(570, 320, 291, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setGeometry(QtCore.QRect(470, 180, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_8.setGeometry(QtCore.QRect(450, 400, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_8.setGeometry(QtCore.QRect(570, 180, 291, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 50, 191, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(450, 50, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setGeometry(QtCore.QRect(182, 400, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 200, 301, 181))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(460, 130, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_22.setGeometry(QtCore.QRect(570, 120, 291, 41))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_11 = QtWidgets.QLabel(self.tab_6)
        self.label_11.setGeometry(QtCore.QRect(50, 60, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_31 = QtWidgets.QLabel(self.tab_6)
        self.label_31.setGeometry(QtCore.QRect(50, 130, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setGeometry(QtCore.QRect(20, 180, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_11)
        self.tabWidget_4.setGeometry(QtCore.QRect(-10, 0, 921, 491))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_12)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 0, 911, 401))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(3)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_28.setGeometry(QtCore.QRect(680, 420, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_23.setGeometry(QtCore.QRect(330, 60, 191, 41))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_22.setGeometry(QtCore.QRect(360, 270, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_9 = QtWidgets.QLabel(self.tab_13)
        self.label_9.setGeometry(QtCore.QRect(210, 70, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_30 = QtWidgets.QLabel(self.tab_13)
        self.label_30.setGeometry(QtCore.QRect(210, 130, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_24.setGeometry(QtCore.QRect(330, 120, 191, 41))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_32 = QtWidgets.QLabel(self.tab_13)
        self.label_32.setGeometry(QtCore.QRect(230, 190, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_25.setGeometry(QtCore.QRect(330, 180, 191, 41))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_23.setGeometry(QtCore.QRect(500, 350, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_28.setGeometry(QtCore.QRect(200, 40, 261, 41))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_24.setGeometry(QtCore.QRect(530, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_25.setGeometry(QtCore.QRect(232, 350, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_41 = QtWidgets.QLabel(self.tab_14)
        self.label_41.setGeometry(QtCore.QRect(120, 50, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_33 = QtWidgets.QLabel(self.tab_14)
        self.label_33.setGeometry(QtCore.QRect(260, 130, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_14)
        self.label_34.setGeometry(QtCore.QRect(280, 260, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_26.setGeometry(QtCore.QRect(370, 120, 221, 41))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_27.setGeometry(QtCore.QRect(370, 250, 221, 41))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_29.setGeometry(QtCore.QRect(370, 180, 221, 41))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_35 = QtWidgets.QLabel(self.tab_14)
        self.label_35.setGeometry(QtCore.QRect(260, 190, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.tabWidget_4.addTab(self.tab_14, "")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(40, 0, 391, 481))
        self.groupBox.setObjectName("groupBox")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(70, 100, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(80, 160, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(30, 280, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(70, 220, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(170, 90, 171, 41))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(170, 150, 171, 41))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_10.setGeometry(QtCore.QRect(170, 210, 171, 41))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_11.setGeometry(QtCore.QRect(170, 270, 171, 41))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(200, 330, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 0, 421, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(60, 40, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(160, 70, 171, 31))
        self.lineEdit_12.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(70, 80, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(160, 30, 171, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_12.setGeometry(QtCore.QRect(190, 107, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(470, 180, 421, 311))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_15.setGeometry(QtCore.QRect(168, 150, 171, 31))
        self.lineEdit_15.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setGeometry(QtCore.QRect(192, 240, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(80, 160, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_14.setGeometry(QtCore.QRect(168, 100, 171, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(40, 200, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_17.setGeometry(QtCore.QRect(170, 50, 171, 31))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(170, 200, 171, 31))
        self.lineEdit_16.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(70, 60, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(80, 110, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 911, 481))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_19.setGeometry(QtCore.QRect(200, 30, 241, 41))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_15.setGeometry(QtCore.QRect(552, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 110, 901, 341))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_4.setGeometry(QtCore.QRect(-2, 110, 901, 341))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_20.setGeometry(QtCore.QRect(180, 30, 251, 41))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_27 = QtWidgets.QLabel(self.tab_8)
        self.label_27.setGeometry(QtCore.QRect(40, 40, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Armenian")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_16.setGeometry(QtCore.QRect(540, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_17.setGeometry(QtCore.QRect(550, 27, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_5.setGeometry(QtCore.QRect(-2, 110, 901, 341))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(1)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_21.setGeometry(QtCore.QRect(180, 30, 241, 41))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_28 = QtWidgets.QLabel(self.tab_9)
        self.label_28.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Armenian")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(650, 40, 381, 511))
        self.groupBox_3.setStyleSheet("background-color: rgb(210, 255, 196);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(50, 40, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(62, 140, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(48, 47, 47);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_18.setGeometry(QtCore.QRect(232, 140, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_19.setGeometry(QtCore.QRect(60, 340, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("\n"
"background-color: rgb(50, 50, 50);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_20.setGeometry(QtCore.QRect(230, 340, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("background-color: rgb(209, 219, 203);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 260, 71, 41))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(20, 300, 71, 51))
        self.pushButton_26.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/auth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_26.setIcon(icon5)
        self.pushButton_26.setIconSize(QtCore.QSize(60, 50))
        self.pushButton_26.setObjectName("pushButton_26")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(40, 190, 41, 20))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(40, 270, 41, 16))
        self.label_40.setObjectName("label_40")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(30, 350, 61, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(30, 440, 61, 20))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(30, 530, 55, 16))
        self.label_44.setObjectName("label_44")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "Enter Item title"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "retrieve"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "rent"))
        self.pushButton_14.setText(_translate("MainWindow", "Add"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item name"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Till"))
        self.label_26.setText(_translate("MainWindow", "Days"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_10.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_10.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_10.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_10.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_10.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_10.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_10.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_10.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_10.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_10.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_10.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_10.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_10.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_10.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_10.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_10.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_10.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_10.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_10.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_10.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_10.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_10.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_10.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_10.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_10.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_10.setItemText(30, _translate("MainWindow", "31"))
        self.label_25.setText(_translate("MainWindow", "Type"))
        self.lineEdit_30.setPlaceholderText(_translate("MainWindow", "Enter client name"))
        self.pushButton_29.setText(_translate("MainWindow", "Export Operation to Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Item title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Location"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Publisher"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Item price"))
        self.pushButton_27.setText(_translate("MainWindow", "Export Item to Excel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "All Item"))
        self.pushButton_7.setText(_translate("MainWindow", "Save"))
        self.label_3.setText(_translate("MainWindow", "Item title"))
        self.label_4.setText(_translate("MainWindow", "Item code"))
        self.label_5.setText(_translate("MainWindow", "Category"))
        self.label_6.setText(_translate("MainWindow", "Location"))
        self.label_7.setText(_translate("MainWindow", "Publisher"))
        self.label_8.setText(_translate("MainWindow", "Item price"))
        self.label_36.setText(_translate("MainWindow", "Description"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Add new Item"))
        self.label_10.setText(_translate("MainWindow", "Publisher"))
        self.label_12.setText(_translate("MainWindow", "Location"))
        self.label_13.setText(_translate("MainWindow", "Item price"))
        self.label_14.setText(_translate("MainWindow", "Category"))
        self.pushButton_8.setText(_translate("MainWindow", "Save"))
        self.pushButton_9.setText(_translate("MainWindow", "Search"))
        self.pushButton_10.setText(_translate("MainWindow", "Delete"))
        self.label_29.setText(_translate("MainWindow", "Item code"))
        self.label_11.setText(_translate("MainWindow", "Item title"))
        self.label_31.setText(_translate("MainWindow", "Item title"))
        self.label_37.setText(_translate("MainWindow", "Description"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Edit or delete a Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client name"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client email"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Client ID"))
        self.pushButton_28.setText(_translate("MainWindow", "Export Client to Excel"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "All clients"))
        self.pushButton_22.setText(_translate("MainWindow", "Save"))
        self.label_9.setText(_translate("MainWindow", "Client Name"))
        self.label_30.setText(_translate("MainWindow", "Client Email"))
        self.label_32.setText(_translate("MainWindow", "Client ID"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Add new client"))
        self.pushButton_23.setText(_translate("MainWindow", "Save Client data"))
        self.pushButton_24.setText(_translate("MainWindow", "Search"))
        self.pushButton_25.setText(_translate("MainWindow", "Delete"))
        self.label_41.setText(_translate("MainWindow", "Client ID"))
        self.label_33.setText(_translate("MainWindow", "Client Name"))
        self.label_34.setText(_translate("MainWindow", "Client ID"))
        self.label_35.setText(_translate("MainWindow", "Client Email"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("MainWindow", "Edit or delete a client"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Page"))
        self.groupBox.setTitle(_translate("MainWindow", "Add new user"))
        self.label_15.setText(_translate("MainWindow", "Username"))
        self.label_16.setText(_translate("MainWindow", "Email ID"))
        self.label_17.setText(_translate("MainWindow", "Password again"))
        self.label_18.setText(_translate("MainWindow", "Password"))
        self.pushButton_11.setText(_translate("MainWindow", "Add user"))
        self.groupBox_2.setTitle(_translate("MainWindow", "User Login "))
        self.label_19.setText(_translate("MainWindow", "Username"))
        self.label_20.setText(_translate("MainWindow", "Password"))
        self.pushButton_12.setText(_translate("MainWindow", "Login"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Edit user information"))
        self.pushButton_13.setText(_translate("MainWindow", "Edit user data"))
        self.label_24.setText(_translate("MainWindow", "Password"))
        self.label_22.setText(_translate("MainWindow", "Password again"))
        self.label_21.setText(_translate("MainWindow", "Username"))
        self.label_23.setText(_translate("MainWindow", "Email ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.label_2.setText(_translate("MainWindow", "New category name"))
        self.pushButton_15.setText(_translate("MainWindow", "Add new category"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category name"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Category"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Location name"))
        self.label_27.setText(_translate("MainWindow", "New Location"))
        self.pushButton_16.setText(_translate("MainWindow", "Add new Location"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Location"))
        self.pushButton_17.setText(_translate("MainWindow", "Add new publisher"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Publisher name"))
        self.label_28.setText(_translate("MainWindow", "New publisher name"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Publisher"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.label.setText(_translate("MainWindow", "Apply New Theme"))
        self.pushButton_6.setText(_translate("MainWindow", "Dark Blue"))
        self.pushButton_18.setText(_translate("MainWindow", "Dark Gray"))
        self.pushButton_19.setText(_translate("MainWindow", "Dark Orange"))
        self.pushButton_20.setText(_translate("MainWindow", "QDark"))
        self.pushButton_21.setText(_translate("MainWindow", "CLOSE >"))
        self.label_38.setText(_translate("MainWindow", "DAY TO DAY"))
        self.label_39.setText(_translate("MainWindow", "ITEM"))
        self.label_40.setText(_translate("MainWindow", "USER"))
        self.label_42.setText(_translate("MainWindow", "CLIENTS"))
        self.label_43.setText(_translate("MainWindow", "MODIFY"))
        self.label_44.setText(_translate("MainWindow", "THEME"))

import icon_rc
